name: Mamiko
favicon: null
layout_spectrum: 0.66042
typography_spectrum: 0.47313
title: feel.write.read
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80becb'
    - '#abe8eb'
    - '#705865'
    - '#dbabad'
    - '#6f807a'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5788556914776564
purpose: []
