title: feel.write.read
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4480287
  brandStrength: 1
  lightness: 0.6236559
  brandColors:
    - '#9ECBD0'
    - '#F15A23'
    - '#FFFFFF'
    - '#21201E'
    - '#BDA391'
  rhythmicContrast: 0.3315412
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Mamiko
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.47313
layout_spectrum: 0.1863799
